
BIN = test-imu

OBJECTS = \
	$(patsubst %.c,%.o,$(wildcard ../*.c)) \
	main.o

CFLAGS += -Wall \
	-Wextra \
	-Werror \
	-O3

LDFLAGS +=

all: $(BIN)

$(BIN): $(OBJECTS)
	gcc $(OBJECTS) $(LDFLAGS) -o $@

%.o: %.c
	gcc $(CFLAGS) -c $< -o $@
