BIN = test-imu

OBJECTS = \
	$(patsubst %.c,%.o,$(wildcard ../*.c)) \
	main.o

CFLAGS += \
	-Wall \
	-Wextra \
	-Werror \
	-O3

LDFLAGS +=

all: $(BIN)

$(BIN): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
